name: Node.js CI

on: [push]

jobs:
  run:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      CI: true
      OS: ${{ matrix.os }}
      NODE: '14.21'

    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1
    - name: Setup
      run: npm ci --no-audit
    - name: Lint
      run: npm run lint --if-present
    - name: Test
      run: npm test
    - name: Build
      run: npm run build --if-present
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage/lcov.info
        flags: unittests
        env_vars: OS,NODE
        name: codecov-umbrella
        fail_ci_if_error: true
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true
